/**
 *
 *  Token.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace client
{
class Client;

class Token
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _client_id;
        static const std::string _access_token;
        static const std::string _refresh_token;
        static const std::string _access_token_expire;
        static const std::string _scope;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Token(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Token(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Token(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Token() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column client_id  */
    ///Get the value of the column client_id, returns the default value if the column is null
    const std::string &getValueOfClientId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientId() const noexcept;
    ///Set the value of the column client_id
    void setClientId(const std::string &pClientId) noexcept;
    void setClientId(std::string &&pClientId) noexcept;
    void setClientIdToNull() noexcept;

    /**  For column access_token  */
    ///Get the value of the column access_token, returns the default value if the column is null
    const std::string &getValueOfAccessToken() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAccessToken() const noexcept;
    ///Set the value of the column access_token
    void setAccessToken(const std::string &pAccessToken) noexcept;
    void setAccessToken(std::string &&pAccessToken) noexcept;
    void setAccessTokenToNull() noexcept;

    /**  For column refresh_token  */
    ///Get the value of the column refresh_token, returns the default value if the column is null
    const std::string &getValueOfRefreshToken() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRefreshToken() const noexcept;
    ///Set the value of the column refresh_token
    void setRefreshToken(const std::string &pRefreshToken) noexcept;
    void setRefreshToken(std::string &&pRefreshToken) noexcept;
    void setRefreshTokenToNull() noexcept;

    /**  For column access_token_expire  */
    ///Get the value of the column access_token_expire, returns the default value if the column is null
    const std::string &getValueOfAccessTokenExpire() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAccessTokenExpire() const noexcept;
    ///Set the value of the column access_token_expire
    void setAccessTokenExpire(const std::string &pAccessTokenExpire) noexcept;
    void setAccessTokenExpire(std::string &&pAccessTokenExpire) noexcept;
    void setAccessTokenExpireToNull() noexcept;

    /**  For column scope  */
    ///Get the value of the column scope, returns the default value if the column is null
    const std::string &getValueOfScope() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getScope() const noexcept;
    ///Set the value of the column scope
    void setScope(const std::string &pScope) noexcept;
    void setScope(std::string &&pScope) noexcept;
    void setScopeToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    Client getClient(const drogon::orm::DbClientPtr &clientPtr) const;
    void getClient(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(Client)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Token>;
    friend drogon::orm::BaseBuilder<Token, true, true>;
    friend drogon::orm::BaseBuilder<Token, true, false>;
    friend drogon::orm::BaseBuilder<Token, false, true>;
    friend drogon::orm::BaseBuilder<Token, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Token>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> clientId_;
    std::shared_ptr<std::string> accessToken_;
    std::shared_ptr<std::string> refreshToken_;
    std::shared_ptr<std::string> accessTokenExpire_;
    std::shared_ptr<std::string> scope_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "client_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "access_token,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "refresh_token,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "access_token_expire,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "scope,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace client
} // namespace drogon_model
